### ISSUE TITLE
Odoo v10 Error: 502

### ISSUE THREAD

**Issue by cezarsantanna-zz** [fnegrini/jasper_odoo#3]
Assim que reinicio o serviço do Odoo e faço o acesso ele apresenta a tela com erro 502 e para.
Abaixo as linhas do log:

`2017-08-04 19:06:41,115 788 DEBUG ? odoo.http: Loading report_jasper_base
2017-08-04 19:06:41,151 775 DEBUG odoo_prd odoo.service.server: Worker (788) unregistered
2017-08-04 19:06:41,155 804 INFO odoo_prd odoo.service.server: Worker WorkerHTTP (804) alive`

Estou utilizando o Odoo v10 no Ubuntu 16.04
Módulos instalados:
base, report, report_py3o

Tudo funciona bem até eu inserir o diretório do jasper_odoo/odoo no addon_path do arquivo de configuração!

Se puder ajudar agradeço!

**Comment by fnegrini** [comment]
Olá,

Chegou a seguir os passos pré-instalação? Necessário instalar alguns pacotes python e configurar variáveis de ambiente

**Comment by cezarsantanna-zz** [comment]
Estas são as versões instaladas
Cython (0.26)
pyjnius (1.1.1)
dicttoxml (1.7.4)

Esta é a entrada no systemd para start do odoo, e passagem das variáveis de ambiente
[Unit]
Description=Odoo
After=postgresql.service
[Service]
Type=simple
User=odoo_prd
Group=odoo_prd
Environment=JAVA_HOME=/usr/lib/jvm/default-java
Environment=CLASSPATH=/opt/odoo_dev/jasper_odoo/java/*
ExecStart=/opt/virtualenvs/odoo_prd/bin/python /opt/odoo_dev/odoo/odoo-bin -c /etc/odoo_prd/odoo_prd.conf
[Install]
WantedBy=multi-user.target

Tem mais alguma informação que posso fornecer para facilitar a descoberta do problema?

**Comment by cezarsantanna-zz** [comment]
`2017-08-11` 15:17:39,115 15721 DEBUG ? odoo.http: Loading report_jasper_base
Error occurred during initialization of VM
Could not allocate metaspace: 1073741824 bytes
2017-08-11 15:17:39,144 15711 DEBUG odoo_prd odoo.service.server: Worker (15721) unregistered
2017-08-11 15:17:39,149 15740 INFO odoo_prd odoo.service.server: Worker WorkerHTTP (15740) alive`

Último teste

**Comment by fnegrini** [comment]
Acho que identifiquei o problema. Fiz todo o desenvolvimento pelo Eclipse onde as variáveis de ambiente são inicializadas corretamente, mas quando o Odoo é executado como serviço as variáveis de ambiente não são carregadas dando erro na biblioteca pyjnius. Já estou verificando uma correção para o problema. Comunico por aqui quando tiver corrigido.

**Comment by fnegrini** [comment]
@cezarsantanna 

Consegui resolver o problema incluindo os seguintes comandos no arquivo daemon do odoo (que fica em /etc/init.d):

export JAVA_HOME="/usr/lib/jvm/default-java"
export CLASSPATH="/opt/odoo/jasper/jasper_odoo/java/*"

Consegue alterar e verificar se funciona pra você?

**Comment by cezarsantanna-zz** [comment]
Estou utilizando o Systemd e teoricamente já estaria atribuindo estas
variáveis de ambiente!

Vou verificar a configuração do Systemd e depois atualizo a solução!


Eng Cezar José Sant'Anna Junior, MSc. PMP. PRINCE2 Practitioner
Cel: (011) 94245-4999
Skype: cezar.santanna
E-mail: cezar.santanna@gmail.com
br.linkedin.com/in/cezarsantanna/

Em 11 de agosto de 2017 17:15, Fabio Negrini <notifications@github.com>
escreveu:

**Comment by fnegrini** [comment]
Tenho uma versão hosteada funcionando. Se quiser testar, está em:

http://165.227.64.7:8069
Database: JASPER
user: admin
senha: 1

A instalação já inclui um relatório de usuários. Entre no menu usuários, marque um ou vários e solicite a impressão do relatório de demonstração.

**Comment by cezarsantanna-zz** [comment]
Qual versão do java você está utilizando, estou utilizando `openjdk version "1.8.0_131"` e continuo tendo problema, mesmo quando inicio via prompt, me parece ser um problema da configuração do java na minha máquina, pois o erro permanece:
`2017-08-14 14:24:13,528 29298 DEBUG ? odoo.http: Loading report_jasper_base
Error occurred during initialization of VM
Could not allocate metaspace: 1073741824 bytes`
Tem alguma sugestão do que poderia estar causando este problema no java, achei alguns bugs relacionados:
[https://stackoverflow.com/questions/33793620/java-what-determines-the-maximum-max-heap-size-possible-in-a-linux-machine](url)

**Comment by fnegrini** [comment]
Estou exatamente na mesma versão de Java que a sua.
No repositório existe a pasta test com três programas de exemplo: sample_01.py, sample_02.py e sample_03.py. Entre num prompt de comando, rode diretamente pelo python qualquer um destes programas e cole o resultado pra eu analisar.

**Comment by cezarsantanna-zz** [comment]
~/TemosOdoo/jasper/jasper_odoo/test$ python sample_01.py
Aug 14, 2017 12:25:58 PM
net.sf.jasperreports.engine.export.PdfGlyphRenderer determinePatchedItext
WARNING: Unpatched iText found, cannot use glyph rendering

~/TemosOdoo/jasper/jasper_odoo/test$ python sample_02.py
Traceback (most recent call last):
 File "sample_02.py", line 24, in <module>
   jasper = JasperInterface(files, {}, TMP_DIRECTORY)
 File "../odoo/report_jasper_base/models/JasperInterface.py", line 126, in
__init__
   self.compiled_design[design_name] = compile_jrxml(self.tempdir,
jrxml_list[design_name])
 File "../odoo/report_jasper_base/models/JasperInterface.py", line 76, in
compile_jrxml
   file = stream_to_java_file(tempdir, xml.toprettyxml(), 'xml')
 File "../odoo/report_jasper_base/models/JasperInterface.py", line 64, in
stream_to_java_file
   pfile.write(stream)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa4' in
position 4640: ordinal not in range(128)

~/TemosOdoo/jasper/jasper_odoo/test$ python sample_03.py
Aug 14, 2017 12:28:39 PM
net.sf.jasperreports.engine.export.PdfGlyphRenderer determinePatchedItext
WARNING: Unpatched iText found, cannot use glyph rendering

Diretório onde o jasper_odoo está:
/opt/odoo_prd/TemosOdoo/jasper/jasper_odoo/test

echo $CLASSPATH
/opt/odoo_prd/TemosOdoo/jasper/jasper_odoo/java/batik-1.9.jar
/opt/odoo_prd/TemosOdoo/jasper/jasper_odoo/java/com.lowagie.text-2.1.7.jar
/opt/odoo_prd/TemosOdoo/jasper/jasper_odoo/java/commons-beanutils-1.9.3.jar
/opt/odoo_prd/TemosOdoo
/jasper/jasper_odoo/java/commons-collections-3.2.2.jar
/opt/odoo_prd/TemosOdoo/jasper/jasper_odoo/java/commons-digester-2.1.jar
/opt/odoo_prd/TemosOdoo/jasper/jasper_odoo/java/commons-lang3-3.5.jar
/opt/odoo_prd/TemosOdoo/jasper/jasper_
odoo/java/commons-logging-1.2.jar
/opt/odoo_prd/TemosOdoo/jasper/jasper_odoo/java/httpcore-4.4.6.jar
/opt/odoo_prd/TemosOdoo/jasper/jasper_odoo/java/jackson-annotations-2.8.3.jar
/opt/odoo_prd/TemosOdoo/jasper/jasper_odoo/java/jackson-c
ore-2.8.3.jar
/opt/odoo_prd/TemosOdoo/jasper/jasper_odoo/java/jackson-databind-2.8.3.jar
/opt/odoo_prd/TemosOdoo/jasper/jasper_odoo/java/jasperreports-6.3.1.jar
/opt/odoo_prd/TemosOdoo/jasper/jasper_odoo/java/poi-3.16.jar /opt/odoo_prd/
TemosOdoo/jasper/jasper_odoo/java/xalan-2.7.1.jar

echo $JAVA_HOME
/usr/lib/jvm/default-java

Python 2.7.12


Eng Cezar José Sant'Anna Junior, MSc. PMP. PRINCE2 Practitioner
Cel: (011) 94245-4999
Skype: cezar.santanna
E-mail: cezar.santanna@gmail.com
br.linkedin.com/in/cezarsantanna/

2017-08-14 12:17 GMT-03:00 Fabio Negrini <notifications@github.com>:

**Comment by fnegrini** [comment]
Aparentemente está tudo ok. O sample_02 está com um problema, mas de fato não interfere na funcionalidade dele no odoo. Estes avisos são da renderização do jrxml, sinal de que conseguiu gerar os arquivos resultados dos testes. Já tentou inserir os comandos "EXPORT"?

**Comment by cezarsantanna-zz** [comment]
Já inseri o EXPORT das variáveis, inclusive executei o Odoo direto pela
linha de comando em um terminal onde as variáveis estavam setadas
corretamente e mesmo assim dá o erro de memória da VM, acredito que deva
ser alguma configuração do JDK no servidor, não tenho muita experiência com
o java, por isto acabo ficando um pouco perdido!

Você chegou a olhar o link que coloquei na mensagem?


Eng Cezar José Sant'Anna Junior, MSc. PMP. PRINCE2 Practitioner
Cel: (011) 94245-4999
Skype: cezar.santanna
E-mail: cezar.santanna@gmail.com
br.linkedin.com/in/cezarsantanna/

Em 14 de agosto de 2017 15:57, Fabio Negrini <notifications@github.com>
escreveu:

**Comment by fnegrini** [comment]
Veja este post que encontrei em uma busca:
http://omaryahir.blogspot.com.br/2014/12/error-occurred-during-initialization-of.html

Ele comenta de dois comandos:
java -XX:CompressedClassSpaceSize=10m -version
java -XX:-UseCompressedClassPointers -version

**Comment by cezarsantanna-zz** [comment]
Quais são seus parâmetros de limit_memory_hard e limit_memory_soft,
aumentando estes parâmetros consegui resolver o problemas de memória, mas
dai apareceu este:

ImportError: No module named dbus.proxies

Qual pacote supre a dependência dbus.proxies



Eng Cezar José Sant'Anna Junior, MSc. PMP. PRINCE2 Practitioner
Cel: (011) 94245-4999
Skype: cezar.santanna
E-mail: cezar.santanna@gmail.com
br.linkedin.com/in/cezarsantanna/

2017-08-14 17:03 GMT-03:00 Fabio Negrini <notifications@github.com>:

**Comment by fnegrini** [comment]
Não sei os valores destes parâmetros. Como vejo?
Sobre o dbus, é o pacote python-dbus, insala com o comando:
sudo apt-get install python-dbus

**Comment by fnegrini** [comment]
Conseguiu fazer funcionar?
